version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "⬆️"
    assignees:
      - "tomtuv"
    groups:
      npm:
        patterns:
          - "*"
